name: 'Setup Agda'
author: 'Wen Kokke'
description: 'Set up a specific version of Agda.'
inputs:
  agda-version:
    description: "The Agda version. Can be 'nightly', 'latest', a specific version number (e.g., 2.6.2.2), a partial version number (e.g., 2.6), or a git commit hash."
    required: true
    default: 'latest'
  # The following inputs are taken from actions/haskell/setup:
  ghc-version:
    required: false
    description: 'Version of GHC to use. If set to "latest", it will always get the latest stable version. If set to "head", it will always get the latest build of GHC.'
    default: 'latest'
  cabal-version:
    required: false
    description: 'Version of Cabal to use. If set to "latest", it will always get the latest stable version.'
    default: 'latest'
  stack-version:
    required: false
    description: 'Version of Stack to use. If set to "latest", it will always get the latest stable version.'
    default: 'latest'
  enable-stack:
    required: false
    description: 'If specified, will setup Stack'
  stack-no-global:
    required: false
    description: 'If specified, enable-stack must be set. Prevents installing GHC and Cabal globally'
  stack-setup-ghc:
    required: false
    description: 'If specified, enable-stack must be set. Will run stack setup to install the specified GHC'
  disable-matcher:
    required: false
    description: 'If specified, disables match messages from GHC as GitHub CI annotations'
outputs: {}
runs:
  using: 'node16'
  main: 'dist/index.js'
