name: 'Setup Agda'
author: 'Wen Kokke'
description: 'Set up a specific version of Agda.'
inputs:
  agda-version:
    default: 'latest'
    description: |
      The Agda version. Can be "latest" or a specific version number (e.g., 2.6.2.2).
    required: true
  bdist-compress-exe:
    description: |
      If specified, the executables are compressed with UPX (https://upx.github.io).

      Only used when "bdist-upload" is specified.
    required: false
  bdist-name:
    description: |
      If specified, will be used as a name for the binary distribution package.

      The value is interpreted as a template (https://mustache.github.io/).
      The template may use {{agda-version}}, {{cabal-version}}, {{ghc-version}},
      {{icu-version}}, {{stack-version}}, and {{upx-version}}, which will be
      replaced by the concrete versions, if installed, and to {{arch}},
      {{platform}}, and {{release}}, which will be replaced by the system
      architecture, operating system, and operating system release, as returned
      by the corresponding NodeJS functions (https://nodejs.org/api/os.html).

      Only used when "bdist-upload" is specified.
    required: false
  bdist-upload:
    description: |
      If specified, will upload a binary distribution for the specified Agda version.
    required: false
  disable-cluster-counting:
    description: |
      If specified, build without cluster counting.
    required: false
  force-build:
    description: |
      If specified, always build from source.
    required: false
  force-no-build:
    description: |
      If specified, never build from source.
    required: false
  ghc-version-match-exact:
    description: |
      If specified, requires an exact match for the GHC version.

      By default, this action uses the pre-installed version of GHC if it is
      compatible with the requested Agda version (see "ghc-version-range") in
      the major and minor version numbers, ignoring the patch version.
    required: false
  ghc-version-range:
    default: '*'
    description: |
      If specified, restricts the range of allowed GHC versions.

      By default, this action infers the set of compatible GHC versions from
      the "tested-with" field in Agda.cabal (if building with Cabal) or from the
      set of "stack-*.yaml" files (if building with Stack). If specified, this
      inferred set of is then filtered by "ghc-version-range".
    required: false

  # If it is called, following inputs are passed to haskell/actions/setup:
  cabal-version:
    default: 'latest'
    description: 'Version of Cabal to use. If set to "latest", it will always get the latest stable version.'
    required: false
  stack-version:
    default: 'latest'
    description: 'Version of Stack to use. If set to "latest", it will always get the latest stable version.'
    required: false
  enable-stack:
    description: 'If specified, will setup Stack.'
    required: false
  stack-no-global:
    description: 'If specified, enable-stack must be set. Prevents installing GHC and Cabal globally.'
    required: false
  stack-setup-ghc:
    description: 'If specified, enable-stack must be set. Will run stack setup to install the specified GHC.'
    required: false
  disable-matcher:
    description: 'If specified, disables match messages from GHC as GitHub CI annotations.'
    required: false

  # The input 'ghc-version' is included as a workaround for issue #122:
  # https://github.com/haskell/actions/issues/122
  ghc-version:
    default: 'latest'
    description: 'Unsupported. Use "ghc-version-range".'
    required: false

outputs:
  agda-path:
    description: 'The path of the agda executable _directory_.'
  agda-data-path:
    description: 'The path of the agda data _directory_.'
  agda-exe:
    description: 'The path of the agda _executable_.'
  agda-mode-exe:
    description: 'The path of the agda-mode _executable_.'
  haskell-setup:
    description: 'Whether or not actions/haskell/setup was called.'

  # If it is called, the following outputs are set by actions/haskell/setup:
  ghc-path:
    description: 'The path of the ghc executable _directory_.'
  cabal-path:
    description: 'The path of the cabal executable _directory_.'
  stack-path:
    description: 'The path of the stack executable _directory_.'
  cabal-store:
    description: 'The path to the cabal store.'
  stack-root:
    description: 'The path to the stack root (equal to the STACK_ROOT environment variable if it is set; otherwise an OS-specific default).'
  ghc-exe:
    description: 'The path of the ghc _executable_.'
  cabal-exe:
    description: 'The path of the cabal _executable_.'
  stack-exe:
    description: 'The path of the stack _executable_.'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: feather
  color: purple
