name: Build Legacy

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 1 1 *'
  workflow_dispatch:

env:
  BUMP_TEXT_ICU: |
    yq -i '. *+ {"extra-deps": ["text-icu-0.7.1.0"], "configure-options": {"Agda": ["--constraint=text-icu>=0.7.1.0"]}}' $STACK_YAML

jobs:
  build-legacy-2_6_2_1:
    name: Build Agda (2.6.2.1)  on ${{ matrix.os }} with Stack
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.6.2.1)
        uses: ./
        with:
          agda-version: '2.6.2'
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -stack{{{stack-version}}}
          cabal-version: '2.4'
          enable-stack: true
          force-build: true
          ghc-version-match-exact: true

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]

  build-legacy-2_6_2:
    name: Build Agda (2.6.2)  on ${{ matrix.os }} with Stack
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.6.2)
        uses: ./
        with:
          agda-version: '2.6.2'
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -stack{{{stack-version}}}
          cabal-version: '2.4'
          enable-stack: true
          force-build: true
          ghc-version-match-exact: true

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]

  build-legacy-2_6_1_3:
    name: Build Agda (2.6.1.3)  on ${{ matrix.os }} with Stack
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.6.1.3)
        uses: ./
        with:
          agda-version: '2.6.1.3'
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -stack{{{stack-version}}}
          cabal-version: '2.4'
          enable-stack: true
          force-build: true
          ghc-version-match-exact: true
          pre-build-hook: |
            ${{ env.BUMP_TEXT_ICU }}
            cat $STACK_YAML

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]

  build-legacy-2_6_0_1:
    name: Build Agda (2.6.0.1)  on ${{ matrix.os }} with Stack
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.6.0.1)
        uses: ./
        with:
          agda-version: '2.6.0.1'
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -stack{{{stack-version}}}
          cabal-version: '2.4'
          enable-stack: true
          force-build: true
          ghc-version-match-exact: true
          pre-build-hook: |
            ${{ env.BUMP_TEXT_ICU }}
            cat $STACK_YAML

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]

  build-legacy-2_5_4_2:
    name: Build Agda (2.5.4.2)  on ${{ matrix.os }} with Stack
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.5.4.2)
        uses: ./
        with:
          agda-version: '2.5.4.2'
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -stack{{{stack-version}}}
          cabal-version: '2.4'
          enable-stack: true
          force-build: true
          ghc-version-match-exact: true
          pre-build-hook: |
            ${{ env.BUMP_TEXT_ICU }}
            cat $STACK_YAML

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]
