name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: npm install
      - run: npm run all

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        agda-version: ['nightly']

    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./
        with:
          agda-version: ${{ matrix.agda-version }}
