name: Build Bdist

on:
  workflow_dispatch:

jobs:
  build-bdist:
    name: Build Agda ${{ matrix.agda-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04] # [macos-11, ubuntu-20.04, window-2022]
        agda-version:
          [
            '2.4.2.3',
            '2.4.2.4',
            '2.4.2.5',
            '2.5.1.2',
            '2.5.2',
            '2.5.3',
            '2.5.4.2',
            '2.6.0.1',
            '2.6.1.3',
            '2.6.2',
            '2.6.2.1'
          ]
    uses: ./.github/workflows/setup-agda.yml
    with:
      runs-on: ${{ matrix.os }}
      agda-version: ${{ matrix.agda-version }}
      force-build: true
      cabal-version: '3.6'
      bdist-upload: true
      bdist-name: |
        agda-{{{agda-version}}}
            -{{{arch}}}
            -${{ matrix.os }}
            -icu{{{icu-version}}}
