name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: npm install
      - run: npm run all

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        agda-version: ['nightly']
        experimental: [false]
        include:
          - os: ubuntu-latest
            agda-version: 'latest'
            experimental: true
    name: Test
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    if: |
      (matrix.agda-version == 'nightly' && !contains(github.event.head_commit.message, '[skip nightly]')) ||
      (matrix.agda-version == 'latest' && !contains(github.event.head_commit.message, '[skip latest]'))
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          agda-version: ${{ matrix.agda-version }}
