name: build missing

on:
  workflow_dispatch:

jobs:
  # Build Agda 2.5.3 with Cabal:
  build-2_5_3-cabal:
    name: Build Agda (2.5.3) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.5.3)
        uses: ./
        with:
          agda-version: '2.5.3'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version: '8.2.2'
          pre-build-hook: |
            cabal v2-configure $CABAL_CONFIG_ARGS --allow-newer=Cabal
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

  # Build Agda 2.5.2 with Cabal:
  build-2_5_2-cabal:
    name: Build Agda (2.5.2) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.5.2)
        uses: ./
        with:
          agda-version: '2.5.2'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version: '8.0.2'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
