name: build missing

on:
  workflow_dispatch:

jobs:
  # Build Agda 2.6.2.2 with Cabal:
  build-2_6_2_2-cabal:
    name: Build Agda (2.6.2.2) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.6.2.2)
        uses: ./
        with:
          agda-version: '2.6.2.2'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version: '9.2.4'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-13]

  # Build Agda 2.6.2.1 with Cabal:
  build-2_6_2_1-cabal:
    name: Build Agda (2.6.2.1) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.6.2.1)
        uses: ./
        with:
          agda-version: '2.6.2.1'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          # NOTE: We can't use GHC 9.2.4, because it ships with an
          #       incompatible version of bytestring-0.11.2.0.
          ghc-version: '9.0.2'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-13]

  # Build Agda 2.6.2 with Cabal:
  build-2_6_2-cabal:
    name: Build Agda (2.6.2) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.6.2)
        uses: ./
        with:
          agda-version: '2.6.2'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version: '9.0.2'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-13]

  # Build Agda 2.6.1.3 with Cabal:
  build-2_6_1_3-cabal:
    name: Build Agda (2.6.1.3) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.6.1.3)
        uses: ./
        with:
          agda-version: '2.6.1.3'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version: '8.10.7'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-13]

  # Build Agda 2.6.0.1 with Cabal:
  build-2_6_0_1-cabal:
    name: Build Agda (2.6.0.1) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.6.0.1)
        uses: ./
        with:
          agda-version: '2.6.0.1'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version: '8.6.5'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-13]

  # Build Agda 2.5.4.2 with Cabal:
  build-2_5_4_2-cabal:
    name: Build Agda (2.5.4.2) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.5.4.2)
        uses: ./
        with:
          agda-version: '2.5.4.2'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version: '8.4.4'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-13]

  # Build Agda 2.5.3 with Cabal:
  build-2_5_3-cabal:
    name: Build Agda (2.5.3) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.5.3)
        uses: ./
        with:
          agda-version: '2.5.3'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version: '8.2.2'
          pre-build-hook: |
            cabal v2-configure $CABAL_CONFIG_ARGS --allow-newer=Cabal
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-13, window-2022]

  # Build Agda 2.5.2 with Cabal:
  build-2_5_2-cabal:
    name: Build Agda (2.5.2) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.5.2)
        uses: ./
        with:
          agda-version: '2.5.2'
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
          bdist-license-report: true
          bdist-upload: true
          cabal-version: '3.8'
          force-build: true
          force-no-optimise-heavily: ${{ runner.os == 'Windows' }}
          ghc-version: '8.0.2'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-13, window-2022]
