name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: npm install
      - run: npm run all

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        agda-version: ['nightly']
        experimental: [false]
        include:
          - os: ubuntu-latest
            agda-version: 'latest'
            experimental: true
          - os: ubuntu-latest
            agda-version: '2.6.2'
            experimental: true
          - os: ubuntu-latest
            agda-version: '2.5.4'
            experimental: true
    name: Test
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./
        with:
          agda-version: ${{ matrix.agda-version }}
