name: ci nightly

# Building and setting up nightly versions is tested separately from the rest
# of the tests, as it is reliant on the current HEAD of agda/agda:
#
# - Building HEAD can fail if the HEAD of agda/agda doesn't build.
#
# - Setting up nightly version can fail if the deploy.yml workflow
#   on agda/agda does not succeed in publishing a nightly version.

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * *'
  workflow_call:
  workflow_dispatch:

env:
  # A yq script which fixes the amount of memory available for compiling Agda.
  # Used by almost all legacy Agda versions.
  YQ_SCRIPT_ADD_MEMORY: |
    . *+ {
      "ghc-options": {"Agda": "+RTS -M6G -RTS"}
    }

jobs:
  build-nightly-cabal:
    name: Build Agda (nightly) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (nightly)
        uses: ./
        with:
          agda-version: 'HEAD'
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
          force-build: true
          force-no-optimise-heavily: true
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-11, macos-12, windows-2022]

  build-nightly-stack:
    name: Build Agda (nightly) on ${{ matrix.os }} with Stack
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (nightly)
        uses: ./
        with:
          agda-version: 'HEAD'
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
          enable-stack: true
          force-build: true
          force-no-optimise-heavily: true
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-11, macos-12, windows-2022]

  setup-nightly:
    name: Setup Agda (nightly) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Agda
        uses: ./
        with:
          force-no-build: true
          agda-version: 'nightly'
      - name: Test Agda
        run: |
          agda -v0 greet.agda
          agda -v0 hello-world.agda
        shell: sh
        working-directory: tests/agda
    strategy:
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-20.04,
            macos-11,
            macos-12,
            windows-2019,
            windows-2022
          ]
