name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/*.yml'

jobs:
  check-dist:
    name: Check dist
    uses: ./.github/workflows/check-dist.yml

  test-bdist:
    name: Setup Agda on ${{ matrix.os }}
    needs: [check-dist]

    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-20.04,
            macos-11,
            macos-12,
            windows-2019,
            windows-2022
          ]

    uses: ./.github/workflows/setup-agda.yml
    with:
      runs-on: ${{ matrix.os }}
      force-no-build: true
      agda-version: latest

  update-latest:
    name: Update Latest
    needs: [check-dist, test-bdist]
    uses: ./.github/workflows/update-latest.yml
