name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/*.yml'

jobs:
  check-dist:
    name: Check dist
    uses: ./.github/workflows/check-dist.yml

  test-setup-agda:
    name: Setup Agda ${{ matrix.agda-version }}
    needs: [check-dist]

    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-20.04,
            macos-11,
            macos-12,
            windows-2022
          ]
        agda-version: [latest]
        cabal-version: ['3.6']
        upload-bdist: [true]

    uses: ./.github/workflows/build.yml
    with:
      runs-on: ${{ matrix.os }}
      agda-version: ${{ matrix.agda-version }}
      cabal-version: ${{ matrix.cabal-version }}
      upload-bdist: ${{ matrix.upload-bdist }}
      bdist-name: agda-{{agda-version}}-{{arch}-${{ matrix.os }}-icu{{icu-version}}

  update-latest:
    name: Update latest
    needs: [check-dist, test-setup-agda]
    uses: ./.github/workflows/update-latest.yml
