name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/*.yml'

jobs:
  check-dist:
    name: Check dist
    uses: ./.github/workflows/check-dist.yml

  test-setup-latest:
    name: Setup Agda (latest)
    needs: [check-dist]
    uses: ./.github/workflows/test-setup-latest.yml

  test-setup-2_6_2_2:
    name: Setup Agda (2.6.2.2)
    needs: [check-dist, test-setup-latest]
    if: needs.test-setup-latest.outputs.agda-latest-version != '2.6.2.2'
    uses: ./.github/workflows/test-setup-2_6_2_2.yml

  release-latest:
    name: Release Latest
    needs: [check-dist, test-setup-latest]
    uses: ./.github/workflows/release-latest.yml
