name: Test

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/*.yml'

jobs:
  check-dist:
    uses: ./.github/workflows/check-dist.yml

  test-no-build:
    needs: [check-dist]
    uses: ./.github/workflows/update-latest.yml

  update-latest:
    needs: [check-dist, test-no-build]
    uses: ./.github/workflows/update-latest.yml
