name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: npm install
      - run: npm run all

  latest_cabal:
    strategy:
      matrix:
        os_with_name:
          - [ubuntu-latest, Linux]
          - [macos-latest, MacOS]
          - [windows-latest, Windows]
        agda-version: ['latest']
        cabal-version: ['3.6']
        experimental: [true]

    name: Setup Agda ${{ matrix.agda-version }} with Cabal on ${{ matrix.os_with_name[1] }}
    runs-on: ${{ matrix.os_with_name[0] }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v3
      - name: wenkokke/setup-agda
        uses: ./
        with:
          agda-version: ${{ matrix.agda-version }}
          cabal-version: ${{ matrix.cabal-version }}
          upload-bdist: true
          upload-bdist-compress-bin: true

  latest_stack:
    strategy:
      matrix:
        os_with_name:
          - [ubuntu-latest, Linux]
          - [macos-latest, MacOS]
          - [windows-latest, Windows]
        agda-version: ['latest']
        cabal-version: ['3.4']
        experimental: [true]

    name: Setup Agda ${{ matrix.agda-version }} with Stack on ${{ matrix.os_with_name[1] }}
    runs-on: ${{ matrix.os_with_name[0] }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v3
      - name: wenkokke/setup-agda
        uses: ./
        with:
          agda-version: ${{ matrix.agda-version }}
          cabal-version: ${{ matrix.cabal-version }}
          enable-stack: true
