name: ci

on:
  push:
    branches: ['main']
    paths: ['**.ts', '**.js', '**.json', '**.yml']

  pull_request:
    branches: ['main']
    paths: ['**.ts', '**.js', '**.json', '**.yml']
    types: [opened, synchronize, reopened]

jobs:
  build-latest:
    uses: ./.github/workflows/setup-latest.yml

  setup-latest:
    uses: ./.github/workflows/setup-latest.yml

  setup-legacy:
    uses: ./.github/workflows/setup-legacy.yml

  setup-libraries:
    uses: ./.github/workflows/setup-libraries.yml

  release:
    if: ${{ github.event_name == 'push' }}
    needs: [build-latest, setup-latest, setup-legacy, setup-libraries]
    uses: ./.github/workflows/release.yml
