name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/*.yml'

jobs:
  check-dist:
    name: Check dist/
    needs: [build]
    uses: ./.github/workflows/check-dist.yml

  setup-agda:
    name: Setup Agda ${{ matrix.agda-version }}
    needs: [check-dist]

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        agda-version: ['latest']
        include:
          - # Build with Cabal
            cabal-version: '3.6'
            enable-stack: ''
            upload-bdist: 'true'
          - # Build with Stack
            cabal-version: '3.4'
            enable-stack: 'true'
            upload-bdist: ''

    uses: ./.github/workflows/bdist.yml
    with:
      runs-on: ${{ matrix.os }}
      agda-version: ${{ matrix.agda-version }}
      cabal-version: ${{ matrix.cabal-version }}
      enable-stack: ${{ matrix.enable-stack }}
      upload-bdist: ${{ matrix.upload-bdist }}
      # upload-bdist-compress-bin: ''
