name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: npm install
      - run: npm run all

  latest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        agda-version: ['latest']
        experimental: [true]
    name: Test
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v3
      - name: wenkokke/setup-agda
        uses: ./
        with:
          agda-version: ${{ matrix.agda-version }}
          upload-artifact: true
