name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/*.yml'

jobs:
  check-dist:
    uses: ./.github/workflows/check-dist.yml

  test-setup-2_6_2_2:
    needs: [check-dist]
    uses: ./.github/workflows/test-setup-2.6.2.2.yml

  test-setup-latest:
    needs: [check-dist]
    uses: ./.github/workflows/test-setup-latest.yml

  release-latest:
    needs: [check-dist, test-no-build]
    uses: ./.github/workflows/release-latest.yml
