name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/*.yml'

jobs:
  check-dist:
    name: Check dist
    uses: ./.github/workflows/check-dist.yml

  test-setup-latest:
    name: Setup Agda (latest) on ${{ matrix.os }}
    needs: [check-dist]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: setup-agda
        name: Setup Agda (latest)
        uses: ./
        with:
          force-no-build: true
          agda-version: 'latest'
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-20.04,
            macos-11,
            macos-12,
            windows-2019,
            windows-2022
          ]
    # Output the version to which 'latest' resolves,
    # so 'test-setup-version' can skip that version.
    outputs:
      agda-version: ${{ steps.setup-agda.outputs.agda-version }}

  test-setup-version:
    name: Setup Agda (${{ matrix.agda-version }}) on ${{ matrix.os }}
    needs: [check-dist, test-setup-latest]
    if: needs.test-setup-latest.outputs.agda-version != matrix.agda-version
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: setup-agda
        name: Setup Agda (${{ matrix.agda-version }})
        uses: ./
        with:
          force-no-build: true
          agda-version: ${{ matrix.agda-version }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-20.04,
            macos-11,
            macos-12,
            windows-2019,
            windows-2022
          ]
        agda-version: ['2.6.2.2']

  release-latest:
    name: Release Latest
    needs: [check-dist, test-setup-latest]
    uses: ./.github/workflows/release-latest.yml
