name: Release Latest

on:
  workflow_call:

jobs:
  release-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update 'latest' tag
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git tag --force latest
          git push --force --tags origin latest
        shell: bash