name: matrix
on: [push]
jobs:
  check:
    name: Check hello-world-proof.agda
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        agda-version: ['2.6.2.2', '2.6.1.3', '2.6.0.1', '2.5.4.2']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: wenkokke/setup-agda@latest
        with:
          agda-version: ${{ matrix.agda-version }}
          agda-stdlib-version: 'recommended'
      - run: agda hello-world-proof.agda
        working-directory: tests/agda-stdlib
