name: Setup Agda

on:
  workflow_call:
    inputs:
      runs-on:
        default: 'ubuntu-latest'
        description: 'The type of machine to run the job on. Default "ubuntu-latest"'
        required: true
        type: string
      agda-version:
        default: 'latest'
        description: |
          The Agda version. Can be "latest" or a specific version number (e.g., 2.6.2.2).
        required: true
        type: string
      bdist-compress-exe:
        default: ''
        description: |
          If specified, the executables are compressed with UPX (https://upx.github.io).

          Only used when "bdist-upload" is specified.
        required: false
        type: string
      bdist-name:
        default: ''
        description: |
          If specified, will be used as a name for the binary distribution package.

          The value is interpreted as a template (https://mustache.github.io/).
          The template may use {{agda-version}}, {{cabal-version}}, {{ghc-version}},
          {{icu-version}}, {{stack-version}}, and {{upx-version}}, which will be
          replaced by the concrete versions, if installed, and to {{arch}},
          {{platform}}, and {{release}}, which will be replaced by the system
          architecture, operating system, and operating system release, as returned
          by the corresponding NodeJS functions (https://nodejs.org/api/os.html).

          Only used when "bdist-upload" is specified.
        required: false
        type: string
      bdist-upload:
        default: ''
        description: |
          If specified, will upload a binary distribution for the specified Agda version.
        required: false
        type: string
      disable-cluster-counting:
        default: ''
        description: |
          If specified, build without cluster counting.
        required: false
        type: string
      force-build:
        default: ''
        description: |
          If specified, always build from source.
        required: false
        type: string
      force-no-build:
        default: ''
        description: |
          If specified, never build from source.
        required: false
        type: string
      ghc-version-match-exact:
        default: ''
        description: |
          If specified, requires an exact match for the GHC version.

          By default, this action uses the pre-installed version of GHC if it is
          compatible with the requested Agda version (see "ghc-version-range") in
          the major and minor version numbers, ignoring the patch version.
        required: false
        type: string
      ghc-version-range:
        default: '*'
        description: |
          If specified, restricts the range of allowed GHC versions.

          By default, this action infers the set of compatible GHC versions from
          the "tested-with" field in Agda.cabal (if building with Cabal) or from the
          set of "stack-*.yaml" files (if building with Stack). If specified, this
          inferred set of is then filtered by "ghc-version-range".
        required: false
        type: string

      # If it is called, following inputs are passed to haskell/actions/setup:
      cabal-version:
        default: 'latest'
        description: 'Version of Cabal to use. If set to "latest", it will always get the latest stable version.'
        required: false
        type: string
      stack-version:
        default: 'latest'
        description: 'Version of Stack to use. If set to "latest", it will always get the latest stable version.'
        required: false
        type: string
      enable-stack:
        default: ''
        description: 'If specified, will setup Stack.'
        required: false
        type: string
      stack-no-global:
        default: ''
        description: 'If specified, enable-stack must be set. Prevents installing GHC and Cabal globally.'
        required: false
        type: string
      stack-setup-ghc:
        default: ''
        description: 'If specified, enable-stack must be set. Will run stack setup to install the specified GHC.'
        required: false
        type: string
      disable-matcher:
        default: ''
        description: 'If specified, disables match messages from GHC as GitHub CI annotations.'
        required: false
        type: string

  workflow_dispatch:
      runs-on:
        default: 'ubuntu-latest'
        description: 'The type of machine to run the job on. Default "ubuntu-latest"'
        required: true
        type: string
      agda-version:
        default: 'latest'
        description: |
          The Agda version. Can be "latest" or a specific version number (e.g., 2.6.2.2).
        required: true
        type: string
      bdist-compress-exe:
        default: ''
        description: |
          If specified, the executables are compressed with UPX (https://upx.github.io).

          Only used when "bdist-upload" is specified.
        required: false
        type: string
      bdist-name:
        default: ''
        description: |
          If specified, will be used as a name for the binary distribution package.

          The value is interpreted as a template (https://mustache.github.io/).
          The template may use {{agda-version}}, {{cabal-version}}, {{ghc-version}},
          {{icu-version}}, {{stack-version}}, and {{upx-version}}, which will be
          replaced by the concrete versions, if installed, and to {{arch}},
          {{platform}}, and {{release}}, which will be replaced by the system
          architecture, operating system, and operating system release, as returned
          by the corresponding NodeJS functions (https://nodejs.org/api/os.html).

          Only used when "bdist-upload" is specified.
        required: false
        type: string
      bdist-upload:
        default: ''
        description: |
          If specified, will upload a binary distribution for the specified Agda version.
        required: false
        type: string
      disable-cluster-counting:
        default: ''
        description: |
          If specified, build without cluster counting.
        required: false
        type: string
      force-build:
        default: ''
        description: |
          If specified, always build from source.
        required: false
        type: string
      force-no-build:
        default: ''
        description: |
          If specified, never build from source.
        required: false
        type: string
      ghc-version-match-exact:
        default: ''
        description: |
          If specified, requires an exact match for the GHC version.

          By default, this action uses the pre-installed version of GHC if it is
          compatible with the requested Agda version (see "ghc-version-range") in
          the major and minor version numbers, ignoring the patch version.
        required: false
        type: string
      ghc-version-range:
        default: '*'
        description: |
          If specified, restricts the range of allowed GHC versions.

          By default, this action infers the set of compatible GHC versions from
          the "tested-with" field in Agda.cabal (if building with Cabal) or from the
          set of "stack-*.yaml" files (if building with Stack). If specified, this
          inferred set of is then filtered by "ghc-version-range".
        required: false
        type: string

      # If it is called, following inputs are passed to haskell/actions/setup:
      cabal-version:
        default: 'latest'
        description: 'Version of Cabal to use. If set to "latest", it will always get the latest stable version.'
        required: false
        type: string
      stack-version:
        default: 'latest'
        description: 'Version of Stack to use. If set to "latest", it will always get the latest stable version.'
        required: false
        type: string
      enable-stack:
        default: ''
        description: 'If specified, will setup Stack.'
        required: false
        type: string
      stack-no-global:
        default: ''
        description: 'If specified, enable-stack must be set. Prevents installing GHC and Cabal globally.'
        required: false
        type: string
      stack-setup-ghc:
        default: ''
        description: 'If specified, enable-stack must be set. Will run stack setup to install the specified GHC.'
        required: false
        type: string
      disable-matcher:
        default: ''
        description: 'If specified, disables match messages from GHC as GitHub CI annotations.'
        required: false
        type: string

jobs:
  setup-agda:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - name: wenkokke/setup-agda@latest
        uses: ./
        with:
          agda-version: ${{ inputs.agda-version }}
          bdist-name: ${{ inputs.bdist-name }}
          bdist-compress-exe: ${{ inputs.bdist-compress-exe }}
          bdist-upload: ${{ inputs.bdist-upload }}
          disable-cluster-counting: ${{ inputs.disable-cluster-counting }}
          force-build: ${{ inputs.force-build }}
          force-no-build: ${{ inputs.force-no-build }}
          ghc-version-match-exact: ${{ inputs.ghc-version-match-exact }}
          ghc-version-range: ${{ inputs.ghc-version-range }}
          cabal-version: ${{ inputs.cabal-version }}
          stack-version: ${{ inputs.stack-version }}
          enable-stack: ${{ inputs.enable-stack }}
          stack-no-global: ${{ inputs.stack-no-global }}
          stack-setup-ghc: ${{ inputs.stack-setup-ghc }}
          disable-matcher: ${{ inputs.disable-matcher }}
