name: Setup Nightly

on:
  workflow_call:
  workflow_dispatch:

jobs:
  setup-nightly:
    # Unfortunately, nightly releases are somewhat brittle, an they
    # depend on the agda/agda `deploy.yml` workflow succeeding.
    continue-on-error: true

    name: Setup Agda (nightly) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Agda
        uses: ./
        with:
          force-no-build: true
          agda-version: 'nightly'
    strategy:
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-20.04,
            macos-11,
            macos-12,
            windows-2019,
            windows-2022
          ]
