name: test andreasabel/ipl

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-andreasabel-ipl:
    name: Test andreasabel/ipl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Agda
        uses: ./
        with:
          force-no-build: true
          agda-version: '2.6.2.2'
          agda-stdlib-version: '1.7.1'
      - uses: actions/checkout@v3
        with:
          repository: andreasabel/ipl
          ref: 9a6151ad1f0977674b8cc9e9cefb49ae83e8a42a
          path: andreasabel/ipl
      - run: agda Everything.agda
        shell: sh
        working-directory: andreasabel/ipl/src
