name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run all

  test-latest:
    runs-on: ubuntu-latest
    name: Test (latest)
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          agda-version: latest

  test-nightly:
    runs-on: ubuntu-latest
    name: Test (nightly)
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          agda-version: nightly
