name: Build Legacy

on:
  workflow_dispatch:

jobs:
  test-build-legacy-stack:
    name: Build Agda (${{ matrix.agda-version }}) on ${{ matrix.os }} with Stack
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (${{ matrix.agda-version }})
        uses: ./
        with:
          agda-version: ${{ matrix.agda-version }}
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -stack{{{stack-version}}}
          cabal-version: ${{ matrix.cabal-version }}
          enable-stack: true
          force-build: true
          ghc-version-match-exact: true
    strategy:
      matrix:
        os: [ubuntu-20.04]
        agda-version:
          [
            '2.2.0',
            '2.2.10',
            '2.2.2',
            '2.2.4',
            '2.2.6',
            '2.2.8',
            '2.3.0',
            '2.3.0.1',
            '2.3.2',
            '2.3.2.1',
            '2.3.2.2',
            '2.4.0',
            '2.4.0.1',
            '2.4.0.2',
            '2.4.2',
            '2.4.2.1',
            '2.4.2.2',
            '2.4.2.3',
            '2.4.2.4',
            '2.4.2.5',
            '2.5.1.2',
            '2.5.2',
            '2.5.3',
            '2.5.4.2',
            '2.6.0.1',
            '2.6.1.3',
            '2.6.2',
            '2.6.2.1'
          ]
        cabal-version: ['2.4']
