name: Build Agda (latest)

on:
  workflow_dispatch:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * 0'

jobs:
  test-build-latest:
    name: Build Agda (latest) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (latest)
        uses: ./
        with:
          force-build: true
          agda-version: 'latest'
          cabal-version: ${{ matrix.cabal-version }}
          enable-stack: ${{ matrix.enable-stack }}
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-11, macos-12, windows-2022]
        enable-stack: [true, false]
        include:
          - enable-stack: true
            cabal-version: '3.4'
          - enable-stack: false
            cabal-version: '3.6'
