name: Build Legacy

on:
  workflow_dispatch:

# Legacy versions:
#
# Agda versions older than 2.4.2.3 do not support any of the GHC versions which
# are supported by haskell/actions/setup. The oldest GHC version that is still
# supported is 7.10.3. Agda 2.4.2.3 is the first version to be tested against a
# GHC 7.10 version, and Agda 2.4.2.5 is the first to be tested against 7.10.3.
# Therefore, versions older than 2.4.2.3 are unlikely to be easily built.
#
# Prior to Agda 2.4.2.2, Agda did not set the 'tested-with' field in the cabal
# file, so for these versions we cannot automatically determine the compatible
# GHC versions when building with Cabal. That excludes the following versions
# from easily being built with Cabal:
# [
#  "2.2.0",   "2.2.10",  "2.2.2",   "2.2.4",   "2.2.6",   "2.2.8",   "2.3.0",
#  "2.3.0.1", "2.3.2",   "2.3.2.1", "2.3.2.2", "2.4.0",   "2.4.0.1", "2.4.0.2",
#  "2.4.2",   "2.4.2.1"
# ]
#
# Prior to Agda 2.5.2, Agda did not bundle stack-XYZ.yaml files, so for these
# versions we cannot automatically determine the compatible GHC versions and
# the configuration when building with Stack. That excludes the following
# versions from easily being built with Stack:
# [
#  "2.2.0",   "2.2.10",  "2.2.2",   "2.2.4",   "2.2.6",   "2.2.8",   "2.3.0",
#  "2.3.0.1", "2.3.2",   "2.3.2.1", "2.3.2.2", "2.4.0",   "2.4.0.1", "2.4.0.2",
#  "2.4.2",   "2.4.2.1", "2.4.2.2", "2.4.2.3", "2.4.2.4", "2.4.2.5", "2.5.1.2"
# ]
#
# Agda 2.5.2 uses GHC 8.0.1, which is unsupported by haskell/actions/setup.
# We could build this version by requiring Stack to set up GHC, or by using
# GHC 8.0.2, which *is* supported.
#
# Agda 2.5.3 fails to build because it cannot find `alex` and `happy`, which
# is probably due to older versions of Cabal not properly installing build
# tool dependencies. We could build this version by installing `alex` and
# `happy` separately prior to building.

jobs:
  test-build-2_5_2:
    name: Build Agda (2.5.2) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Build Agda (2.5.2)
        uses: ./
        with:
          agda-version: '2.5.2'
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -stack{{{stack-version}}}
          cabal-version: '2.4'
          force-build: true
          ghc-version-match-exact: false
    strategy:
      matrix:
        os: [ubuntu-20.04] # Exclude until experimental build passes: macos-11, windows-2022

  test-build-2_5_3:
    name: Build Agda (2.5.3) on ${{ matrix.os }} with Cabal
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Alex & Happy
        run: |
          cabal update
          cabal install alex
          cabal install happy
        shell: bash
      - name: Build Agda (2.5.3)
        uses: ./
        with:
          agda-version: '2.5.3'
          bdist-upload: true
          bdist-name: |
            agda-{{{agda-version}}}
                -{{{arch}}}
                -${{ matrix.os }}
                -icu{{{icu-version}}}
                -ghc{{{ghc-version}}}
                -cabal{{{cabal-version}}}
                -stack{{{stack-version}}}
          cabal-version: '2.4'
          enable-stack: true
          force-build: true
          ghc-version-match-exact: true
    strategy:
      matrix:
        os: [ubuntu-20.04] # Exclude until experimental build passes: macos-11, windows-2022


  # test-build-2_5_4_2:
  #   name: Build Agda (2.5.4.2) on ${{ matrix.os }} with Stack
  #   runs-on: ${{ matrix.os }}
  #   continue-on-error: true
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build Agda (2.5.4.2)
  #       uses: ./
  #       with:
  #         agda-version: '2.5.4.2'
  #         bdist-upload: true
  #         bdist-name: |
  #           agda-{{{agda-version}}}
  #               -{{{arch}}}
  #               -${{ matrix.os }}
  #               -icu{{{icu-version}}}
  #               -ghc{{{ghc-version}}}
  #               -cabal{{{cabal-version}}}
  #               -stack{{{stack-version}}}
  #         cabal-version: '2.4'
  #         enable-stack: true
  #         force-build: true
  #         ghc-version-match-exact: true
  #   strategy:
  #     matrix:
  #       os: [windows-2022] # Previously built: ubuntu-20.04, macos-11

  # test-build-2_6_0_1:
  #   name: Build Agda (2.6.0.1) on ${{ matrix.os }} with Stack
  #   runs-on: ${{ matrix.os }}
  #   continue-on-error: true
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build Agda (2.6.0.1)
  #       uses: ./
  #       with:
  #         agda-version: '2.6.0.1'
  #         bdist-upload: true
  #         bdist-name: |
  #           agda-{{{agda-version}}}
  #               -{{{arch}}}
  #               -${{ matrix.os }}
  #               -icu{{{icu-version}}}
  #               -ghc{{{ghc-version}}}
  #               -cabal{{{cabal-version}}}
  #               -stack{{{stack-version}}}
  #         cabal-version: '2.4'
  #         enable-stack: true
  #         force-build: true
  #         ghc-version-match-exact: true
  #   strategy:
  #     matrix:
  #       os: [windows-2022] # Previously built: ubuntu-20.04, macos-11

  # test-build-2_6_1_3:
  #   name: Build Agda (2.6.1.3) on ${{ matrix.os }} with Stack
  #   runs-on: ${{ matrix.os }}
  #   continue-on-error: true
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build Agda (2.6.1.3)
  #       uses: ./
  #       with:
  #         agda-version: '2.6.1.3'
  #         bdist-upload: true
  #         bdist-name: |
  #           agda-{{{agda-version}}}
  #               -{{{arch}}}
  #               -${{ matrix.os }}
  #               -icu{{{icu-version}}}
  #               -ghc{{{ghc-version}}}
  #               -cabal{{{cabal-version}}}
  #               -stack{{{stack-version}}}
  #         cabal-version: '2.4'
  #         enable-stack: true
  #         force-build: true
  #         ghc-version-match-exact: true
  #   strategy:
  #     matrix:
  #       os: [windows-2022] # Previously built: ubuntu-20.04, macos-11

  # test-build-2_6_2:
  #   name: Build Agda (2.6.2) on ${{ matrix.os }} with Stack
  #   runs-on: ${{ matrix.os }}
  #   continue-on-error: true
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build Agda (2.6.2)
  #       uses: ./
  #       with:
  #         agda-version: '2.6.2'
  #         bdist-upload: true
  #         bdist-name: |
  #           agda-{{{agda-version}}}
  #               -{{{arch}}}
  #               -${{ matrix.os }}
  #               -icu{{{icu-version}}}
  #               -ghc{{{ghc-version}}}
  #               -cabal{{{cabal-version}}}
  #               -stack{{{stack-version}}}
  #         cabal-version: '2.4'
  #         enable-stack: true
  #         force-build: true
  #         ghc-version-match-exact: true
  #   strategy:
  #     matrix:
  #       os: [windows-2022] # Previously built: ubuntu-20.04, macos-11

  # test-build-2_6_2_1:
  #   name: Build Agda (2.6.2.1) on ${{ matrix.os }} with Stack
  #   runs-on: ${{ matrix.os }}
  #   continue-on-error: true
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build Agda (2.6.2.1)
  #       uses: ./
  #       with:
  #         agda-version: '2.6.2.1'
  #         bdist-upload: true
  #         bdist-name: |
  #           agda-{{{agda-version}}}
  #               -{{{arch}}}
  #               -${{ matrix.os }}
  #               -icu{{{icu-version}}}
  #               -ghc{{{ghc-version}}}
  #               -cabal{{{cabal-version}}}
  #               -stack{{{stack-version}}}
  #         cabal-version: '2.4'
  #         enable-stack: true
  #         force-build: true
  #         ghc-version-match-exact: true
  #   strategy:
  #     matrix:
  #       os: [windows-2022] # Previously built: ubuntu-20.04, macos-11
