name: Update Release

on:
  workflow_run:
    branches: [main]
    workflows: ['Setup 2.6.2.2']
    types: [completed]

jobs:
  update-latest-release:
    # Run 'update-release' if 'test-setup-2_6_2_2' succeeded:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update 'latest' tag
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git tag --force latest
          git push --force --tags origin latest
        shell: bash
