name: Update Release

on:
  # Run 'update-latest-release' if 'setup-legacy' completed:
  workflow_run:
    branches: [main]
    workflows: ['Setup Legacy']
    types: [completed]
  workflow_dispatch:

jobs:
  update-latest-release:
    # Skip 'update-latest-release' if 'setup-legacy' did not succeed:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update 'latest' tag
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git tag --force latest
          git push --force --tags origin latest
        shell: bash
